In [3]:
#Linear Regression
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn import datasets

boston=datasets.load_boston() #creating daset object

#features and labels

X=boston.data
y=boston.target

print(X.shape)
print(X)
print(y.shape)
print(y)

#creating linear regression model

l_reg=linear_model.LinearRegression()
plt.scatter(X.T[5],y)#shows that data is appropriate for linear regression

#model

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

model=l_reg.fit(X_train,y_train)
predictions=model.predict(X_test)
print('Predictions',predictions)
print('R^2',l_reg.score(X,y))#explains to what extent the variance of one variable explains the variance of the second variable.
#So, if the R2 of a model is 0.50, then approximately half of the observed variation can be explained by the model's inputs.
#R^2 is a tatistical measure of how close the data are to the fitted regression line. 

print("coedd:",l_reg.coef_)
#coefficient factor: slope of all our fit trenlines.Scale factor of multiplication of x variable(if y=mx+c,then coefficient factor is m)

print("Intercepts",l_reg.intercept_)


























(506, 13)
[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
(506,)
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 1